# -*- coding: utf-8 -*-
"""
@author: Piet Reyniers
"""

# import dependencies
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from colormath.color_objects import sRGBColor, XYZColor, LabColor
from colormath.color_conversions import convert_color

# input file location
source_path = 'D:/OneDrive - UGent/Teaching_AAP/15_Advanced Sedimentology/2025-2026/20251008_MSCL/20251008_MSCL.out'
output_path = 'D:/OneDrive - UGent/Teaching_AAP/15_Advanced Sedimentology/2025-2026/20251008_MSCL/output.out'
# path to file with the name of the sections in order of scanning
sections_path = 'D:/OneDrive - UGent/Teaching_AAP/15_Advanced Sedimentology/2025-2026/20251008_MSCL/scan_order.txt'

# function to combine 2 rows of the same datapoint with NaN together.
def remove_duplicate_rows(df):
    # Find lines with Nan
    rows_with_nan = pd.isnull(df).any(axis=1).to_numpy().nonzero()

    for i in rows_with_nan[0]:
        # Check if the row with NaN belongs to the same datapoint as previous row.
        if (df["SB DEPTH (cm)"].iloc[i - 1] == df["SB DEPTH (cm)"].iloc[i]
                and df["DateTime"].iloc[i - 1] == df["DateTime"].iloc[i]):
            # Replace NaN of first row of datapoint together with non-NaN of second row of the same datapoint
            df.iloc[i - 1] = df.iloc[i - 1].combine_first(df.iloc[i])

    # Delete all rows with NaN. This method has the disadvantage of removing all lines, even when there is a correct NaN

    return df.dropna()


def mscldata2df(import_path):
    # opens a mscl .out file, as it is generated by the mscl. Removes the metadata at the and adds headers.
    # return dataframe of the data

    # Import data
    rows_to_skip = 13
    mscl_data = pd.read_csv(import_path,
                            sep='\t',
                            skiprows=lambda x: x in range(0, rows_to_skip),
                            header=None,
                            skip_blank_lines=True)


    # add headers (option to add headers in import step but headers of MSCL data file are not the best, take 2 rows)
    headers = ["SB DEPTH (cm)", "SECT_NUM", "SECT DEPTH (cm)", "DateTime", "Core Thickness",
               "Den1 (g/cc)", "MS1 (SI x 10^-5)", "FP", "L*", "a*", "b*", "X", "Y", "Z",
               "Red (595 - 700)", "Green (515 - 595)", "Blue (400 - 515)",
               "360", "370", "380", "390", "400", "410", "420", "430", "440", "450",
               "460", "470", "480", "490", "500", "510", "520", "530", "540", "550",
               "560", "570", "580", "590", "600", "610", "620", "630", "640", "650",
               "660", "670", "680", "690", "700", "710", "720", "730", "740"]
    mscl_data.columns = headers
    

    
    return mscl_data


def plotdata(MSCL_DF, export_folder_path, file, Yaxis):
    # MSCL_DF dataframe with mscl data
    # export_folder_path location to save images
    # file = filename for image
    # Yaxis SB depth or sect depth dependent on what is present in mscl_df.

    ylimTop = MSCL_DF[Yaxis].min()
    ylimBottom = MSCL_DF[Yaxis].max()

    fig = plt.figure(figsize=(16, 9), layout="constrained")

    fig.suptitle(file)

    # plot core thickness
    ax1 = plt.subplot(181)
    plt.plot(MSCL_DF["Core Thickness"], MSCL_DF[Yaxis])
    plt.tick_params('x')
    ax1.set_title("Core Thickness (cm)")
    ax1.grid(True)
    ax1.set_ylim(ylimBottom, ylimTop)

    # plot density data
    ax2 = plt.subplot(182, sharey=ax1)
    plt.plot(MSCL_DF["Den1 (g/cc)"], MSCL_DF[Yaxis])
    plt.tick_params('x')
    ax2.set_title("Density (g/cc)")
    ax2.grid(True)
    ax2.tick_params('y', left=False, labelleft=False)

    # plot fractional porosity
    ax3 = plt.subplot(183, sharey=ax1)
    plt.plot(MSCL_DF["FP"], MSCL_DF[Yaxis])
    plt.tick_params('x')
    ax3.set_title("FP")
    ax3.grid(True)
    ax3.tick_params('y', left=False, labelleft=False)

    # plot MS data
    ax4 = plt.subplot(184, sharey=ax1)
    #extra om nan niet te plotten bij rare data van adv sed=
    #ind = ~np.isnan(np.asarray(MSCL_DF["MS1 (SI x 10^-5)"]))
    #plt.plot(MSCL_DF["MS1 (SI x 10^-5)"][ind], MSCL_DF[Yaxis][ind])
    plt.plot(MSCL_DF["MS1 (SI x 10^-5)"], MSCL_DF[Yaxis])
    plt.tick_params('x')
    ax4.tick_params('y', left=False, labelleft=False)
    ax4.set_title("MS (SI x 10^-5)")
    ax4.grid(True)

    # plot LAB data
    ax5 = plt.subplot(185, sharey=ax1)
    plt.plot(MSCL_DF["L*"], MSCL_DF[Yaxis], label='L*')
    plt.plot(MSCL_DF["a*"], MSCL_DF[Yaxis], label='a*')
    plt.plot(MSCL_DF["b*"], MSCL_DF[Yaxis], label='b*')
    ax5.set_title("LAB")
    ax5.legend()
    ax5.grid(True)
    ax5.tick_params('y', left=False, labelleft=False)

    # plot RGB data
    ax6 = plt.subplot(186, sharey=ax1)
    plt.plot(MSCL_DF["Red (595 - 700)"], MSCL_DF[Yaxis], color='r')
    plt.plot(MSCL_DF["Green (515 - 595)"], MSCL_DF[Yaxis], color='g')
    plt.plot(MSCL_DF["Blue (400 - 515)"], MSCL_DF[Yaxis], color='b')
    ax6.set_title("RGB")
    ax6.grid(True)
    ax6.tick_params('y', left=False, labelleft=False)

    # plot XYZ data
    ax7 = plt.subplot(187, sharey=ax1)
    plt.plot(MSCL_DF["X"], MSCL_DF[Yaxis], color='orange', label='X')
    plt.plot(MSCL_DF["Y"], MSCL_DF[Yaxis], color='purple', label='Y')
    plt.plot(MSCL_DF["Z"], MSCL_DF[Yaxis], color='y', label='Z')
    ax7.set_title("XYZ")
    ax7.legend()
    ax7.grid(True)
    ax7.tick_params('y', left=False, labelleft=False)

    # Create RGB values from LAB
    Lab_val_list = []
    rgb_val_list = []
    # extract LAB from dataframe
    for i in range(len(MSCL_DF["L*"])):
        L = int(MSCL_DF["L*"].iloc[i])
        a = int(MSCL_DF["a*"].iloc[i])
        b = int(MSCL_DF["b*"].iloc[i])
        Lab_val_list.append([L, a, b])

    # convert to RGB values
    for lab_list in Lab_val_list:
        lab = LabColor(*[component for component in lab_list])
        rgb = convert_color(lab, sRGBColor)
        rgb_list = [int(255*color) for color in rgb.get_value_tuple()]
        rgb_val_list.append(rgb_list)

    rgb_val_list = np.array(rgb_val_list)

    # reshape array
    rgb_val_list = rgb_val_list.reshape(-1, 1, 3)

    # create new subplot with colors
    ax8 = plt.subplot(188)
    ax8.imshow(rgb_val_list, aspect=0.1)
    ax8.axis('off')

    # Save the figure
    plt.savefig(export_folder_path + file+"_MSCL.png", dpi=300)


def split2sectionsandplot(mscl_df, section_names, export_path):
    unique_values = mscl_df.SECT_NUM.unique()
    for section_number, section_name in zip(unique_values, section_names):
        subset_df = mscl_df.loc[mscl_df['SECT_NUM'] == section_number]
        filename = section_name.strip("\n") + "_MSCL.csv"
        print(filename)
        print(subset_df.head())
        print(subset_df.tail())
        print(subset_df.shape)
        # Export Data as CSV.
        plotdata(subset_df, export_path, section_name.strip("\n"), "SECT DEPTH (cm)")
        subset_df.to_csv(export_path + filename, index=False)
        

def main():
    data = mscldata2df(source_path)
    data = remove_duplicate_rows(data)

    with open(sections_path, mode='r') as sections:
        split2sectionsandplot(data, sections, output_path)


    
if __name__ == "__main__":
    main()
